### ISSUE TITLE
import gensim error. Uses triu function from scipy.linalg which is deprecated

### ISSUE THREAD

**Issue by KMS07** [piskvorky/gensim#3534] opened 2024-06-03 08:20 UTC
#### Problem description

When importing gensim there is a inner dependency error with triu function of scipy.linalg as its deprecated.

**Comment by piskvorky** [comment] 2024-06-03 08:25
@KMS07 thanks for reporting; already fixed in `master` a while ago, but not released yet.

@mpenkov how about we allocate a few hours time month (June) and do the release? So we don't get this constant trickle of "broken scipy.linalg" tickets if nothing else :)

**Comment by KMS07** [comment] 2024-06-03 08:31
Im trying to execute this `from zeugma import EmbeddingTransformer` which raises the error of triu. Could you provide a way out

**Comment by mpenkov** [comment] 2024-06-03 08:46
@piskvorky Yeah, let's get this thing out the door. Can you set up a meeting on a JST weeknight (other than Monday or Wednesday)?

**Comment by gojomo** [comment] 2024-06-04 15:40
Another consideration: numpy-2.0 with potentially-breaking changes is coming June 16: https://numpy.org/news/#numpy-20-release-date-june-16

Setting up a CI build/test that pulls `numpy==2.0.0rc2` may tell us lots of things needing small tweaks. Given the ABI changes, it may not be possible for the same wheels to support numpy<2.0 and numpy>=2.0 – I'm not sure. 

If a Gensim-4.3.3 with small fixes, including this scipy fix, is imminent, it may make sense to have 4.3.3's declared requirements pin numpy before `2.0` until a Gensim-4.4(?) that works with (& maybe even requires?) numpy-2.0 might give some extra options for coaching users to the right working release.

**Comment by AlessioBolpagni98** [comment] 2024-06-12 08:32
while this problem is solved which gensim installation recommended? if I use the latest version I can not properly import the functions without receiving this error

**Comment by mpenkov** [comment] 2024-06-12 15:00
duplicate of #3525

**Comment by mpenkov** [comment] 2024-06-12 15:01
@AlessioBolpagni98 Use an older scipy install. See the discussion in #3525 for details.

**Closed** 2024-06-12 15:14 UTC
Labels: difficulty easy, impact HIGH, duplicate
