### ISSUE TITLE
doc2vec/word2vec FAST_VERSION is -1 with scipy 0.16.0

### ISSUE THREAD

**Issue by transcranial** [piskvorky/gensim#411] opened 2015-07-30 18:49 UTC
FAST_VERSION is -1 when I install gensim 0.12.1 with scipy 0.16.0, but reverts back to normal with scipy 0.15.1. I presume it's due to scipy.linalg.blas being removed in scipy 0.16.0.

**Comment by piskvorky** [comment] 2015-07-30 19:40
That's right. Duplicate of #382 -- fix welcome!

**Closed by piskvorky** 2015-07-30 19:40 UTC
