### ISSUE TITLE
 Always, each row of  word2vec model  txt format file  starts with word and the rest is vector. But the function save_word2vec_format of the code  make  it starting with index. Is it a Bug?

### ISSUE THREAD

**Issue by rollingdeep** [piskvorky/gensim#3555] opened 2024-07-31 09:49 UTC
https://github.com/piskvorky/gensim/blob/54dfec9909041817371ed96a4a53e36dc1b398d9/gensim/models/keyedvectors.py#L1639C2-L1670C110

``` python
store_order_vocab_keys = self.index_to_key
keys_to_write = itertools.chain(range(0, index_id_count), store_order_vocab_keys)
for key in keys_to_write:
                key_vector = self[key]
                if binary:
                    fout.write(f"{prefix}{key} ".encode('utf8') + key_vector.astype(REAL).tobytes())
                else:
                    fout.write(f"{prefix}{key} {' '.join(repr(val) for val in key_vector)}\n".encode('utf8'))
```
 Always, each row of  word2vec model  txt format file  starts with word and the rest is vector. But the function save_word2vec_format of the code  make  it starting with index. Is it a Bug?

**Comment by rollingdeep** [comment] 2024-07-31 09:54
A easy solution is setting new_model.index_to_key same as new_model.key_to_index. 
``` python
new_model = KeyedVectors(vector_size=model.vector_size)
new_model.index_to_key = {word: idx for idx, word in enumerate(selected_vectors.keys())}
new_model.key_to_index = {word: idx for idx, word in enumerate(selected_vectors.keys())}
new_model.save_word2vec_format(novel_w2v_path, binary=False)
```

**Comment by gojomo** [comment] 2024-08-03 18:02
The elements in `index_to_key` are the keys (words). So the code you've excerpted does the right thing.

You can verify this by using th function, then looking at the resulting file in a text editor. (Something "looking wrong" to you without testing is not a good basis for filing a bug report. Demonstrating an error or incorrect behavior with actual testing is better.)

Your suggested fix would clobber a uniquely useful and compact in-order list of the keys (`index_to_key`) with a less-compact dict duplicate of information already available in the model elsewere.

**Closed by gojomo** 2024-08-03 18:02 UTC

**Comment by rollingdeep** [comment] 2024-11-07 09:36
Something "looking wrong" to you without testing is not a good basis for filing a bug report. No No No.
I test save_word2vec_format function and find the result of "new_model.save_word2vec_format" is not a word2vec format. word2vec format starts with  word and then ' '.join(vector). But excerpted code of the project output is not as expected, it return a text file starting with  index and then ' '.join(vector). So it lack a word information.

**Comment by rollingdeep** [comment] 2024-11-07 09:48
You can see the issue: https://github.com/piskvorky/gensim/issues/2795.
