### ISSUE TITLE
Unable to reproduce Word2vec vectors with a given seed

### ISSUE THREAD

**Issue by d10genes** [piskvorky/gensim#662] opened 2016-04-07 02:02 UTC
If I run the following snippet in the same IPython session, then  I get the same sum repeatedly. Each time I restart the IPython session, however, I get different results.

    import gensim

    sents = '''The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced
    The jury further said in term-end presentments that the City Executive Committee , which had over-all charge of 
    The September-October term jury had been charged by Fulton Superior Court Judge Durwood Pye to investigate reports 
    Only a relative handful of such reports was received '' , the jury said , considering the widespread interest'''.splitlines()
    sents = list(map(str.split, sents))

    wmod = gensim.models.Word2Vec(sents, seed=42, min_count=1)
    print(wmod['The'].sum())
    
Is this expected behavior?

`gensim.__version__ == '0.12.2'`

**Comment by gojomo** [comment] 2016-04-07 04:42
Yes – and particularly if you're using Python 3.x, with `PYTHONHASHSEED`-controlled string-hash randomization on each launch, which will change the iteration-ordering of the vocabulary-dictionary keys. See https://groups.google.com/d/msg/gensim/7eiwqfhAbhs/qC0pmbw5HwAJ for more discussion. 

Not a bug so closing this issue.

**Closed by gojomo** 2016-04-07 04:42 UTC
