### ISSUE TITLE
Bug on Import gensim

### ISSUE THREAD

**Issue by PixelJunkie33** [piskvorky/gensim#3530] opened 2024-05-16 16:16 UTC
#### Problem description

Import Gensim py.env 3.11.3. I tried L pip install gensim==4.1.2 and pip install scipy==1.7.3

#### Steps/code/corpus to reproduce

import gensim
from gensim import corpora
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from nltk.tokenize import word_tokenize

#### Versions

Please provide the output of:

```python
ImportError: cannot import name 'triu' from 'scipy.linalg' (c:\Users\ktpra\AppData\Local\Programs\Python\Python311\Lib\site-packages\scipy\linalg\__init__.py)

```

**Comment by gojomo** [comment] 2024-05-17 03:27
Duplicate of #3525 - there's a workaround there (install a slightly-older scipy) & the next version of Gensim will have a fix.

**Closed by gojomo** 2024-05-17 03:27 UTC
