### ISSUE TITLE
Unable to install on Win 7, Python 3.4.3

### ISSUE THREAD

**Issue by GraphGrail** [piskvorky/gensim#432] opened 2015-08-14 10:25 UTC
Got an error:

C:\Program Files (x86)\PowerCmd>pip install -U gensim
You are using pip version 6.0.8, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting gensim
  Using cached gensim-0.12.1.tar.gz
running egg_info
creating pip-egg-info\gensim.egg-info
writing requirements to pip-egg-info\gensim.egg-info\requires.txt
writing pip-egg-info\gensim.egg-info\PKG-INFO
writing dependency_links to pip-egg-info\gensim.egg-info\dependency_links.txt
writing top-level names to pip-egg-info\gensim.egg-info\top_level.txt
writing manifest file 'pip-egg-info\gensim.egg-info\SOURCES.txt'
warning: manifest_maker: standard file '-c' not found

reading manifest file 'pip-egg-info\gensim.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.sh' under directory '.'
no previously-included directories found matching 'docs\src*'
writing manifest file 'pip-egg-info\gensim.egg-info\SOURCES.txt'
Requirement already up-to-date: numpy>=1.3 in m:\winpython-64bit-3.4.3.2\python-3.4.3.amd64\lib\site-packages (from gensim)
Requirement already up-to-date: scipy>=0.7.0 in m:\winpython-64bit-3.4.3.2\python-3.4.3.amd64\lib\site-packages (from gensim)
Requirement already up-to-date: six>=1.2.0 in m:\winpython-64bit-3.4.3.2\python-3.4.3.amd64\lib\site-packages (from gensim)
Collecting smart-open>=1.2.1 (from gensim)
  Using cached smart_open-1.2.1.tar.gz
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "C:\Users\Joomler\AppData\Local\Temp\pip-build-l4gil7vj\smart-open\setup.py", line 28, in <module>
    long_description = read('README.rst'),
  File "C:\Users\Joomler\AppData\Local\Temp\pip-build-l4gil7vj\smart-open\setup.py", line 21, in read
    return open(os.path.join(os.path.dirname(__file__), fname)).read()
  File "M:\WinPython-64bit-3.4.3.2\python-3.4.3.amd64\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 4345: character maps to <undefined>
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\Joomler\AppData\Local\Temp\pip-build-l4gil7vj\smart-open\setup.py", line 28, in <module>
        long_description = read('README.rst'),
      File "C:\Users\Joomler\AppData\Local\Temp\pip-build-l4gil7vj\smart-open\setup.py", line 21, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "M:\WinPython-64bit-3.4.3.2\python-3.4.3.amd64\lib\encodings\cp1251.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 4345: character maps to <undefined>
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "C:\Users\Joomler\AppData\Local\Temp\pip-build-l4gil7vj\smart-open\setup.py", line 28, in <module>
    
        long_description = read('README.rst'),
    
      File "C:\Users\Joomler\AppData\Local\Temp\pip-build-l4gil7vj\smart-open\setup.py", line 21, in read
    
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    
      File "M:\WinPython-64bit-3.4.3.2\python-3.4.3.amd64\lib\encodings\cp1251.py", line 23, in decode
    
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 4345: character maps to <undefined>
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\Joomler\AppData\Local\Temp\pip-build-l4gil7vj\smart-open

**Comment by piskvorky** [comment] 2015-08-14 12:37
Looks like a duplicate of #428 , recently fixed.

**Closed by piskvorky** 2015-08-14 12:37 UTC

**Comment by GraphGrail** [comment] 2015-08-14 12:53
I solved myself and install successfully http://stackoverflow.com/questions/31996843/how-to-install-gensim-on-windows-7/31998108#31998108

But now i faced with error: (python 3.4.3.2, windows 7)
OverflowError: Python int too large to convert to C long

When i do:
from gensim.models import Word2Vec
from nltk.corpus import brown, movie_reviews, treebank
print('Word2Vec')
b = Word2Vec(brown.sents())
print('b', b)
mr = Word2Vec(movie_reviews.sents())
print('mr', mr)
t = Word2Vec(treebank.sents())
print('t', t)
b_most_similar = b.most_similar('money', topn=5)
print('b_most_similar', b_most_similar)


I have read this but cannot solve:
https://www.kaggle.com/c/word2vec-nlp-tutorial/forums/t/11197/gensim-word2vec-cython-on-windows/85602

**Comment by piskvorky** [comment] 2015-08-14 14:07
That one was solved in #392. With gensim 0.12.1, you should already have the fix active.

So I'm thinking this must be something new... can you paste the full traceback? CC @gojomo

**Comment by GraphGrail** [comment] 2015-08-14 14:15
Fixed myself using this: https://github.com/piskvorky/gensim/issues/321 -  luopuya comment on 5 Jul
So i edited the source file word2vec.py,  from line 336:

    def myhashfxn(obj):
        return hash(obj) % (2 ** 32)

    def __init__(
            self, sentences=None, size=100, alpha=0.025, window=5, min_count=5,
            max_vocab_size=None, sample=0, seed=1, workers=1, min_alpha=0.0001,
            sg=1, hs=1, negative=0, cbow_mean=0, hashfxn=myhashfxn, iter=1, null_word=0):
        """
        Initialize the model from an iterable of `sentences`. Each sentence is a
        list of words (unicode strings) that will be used for training.


I added a function myhashfxn  before  def __init__  
and in  
def __init__  
 changed 
hashfxn=myhashfxn

**Comment by thomasniebler** [comment] 2015-08-28 15:13
Can confirm fix from @GraphGrail.
