### ISSUE TITLE
Strange result when retrieving a not existing word embedding for a document

### ISSUE THREAD

**Issue by claudiogreco** [piskvorky/gensim#520] opened 2015-11-10 12:32 UTC
Hello,

after creating a doc2vec model using the code reported in the tutorial with **python 3.5** and **gensim 0.12.3**, I have wrongly tried to retrieve a missing document, but I have received a strange numpy.ndarray as a result whose shape is (1, 1235, 300), where 1235 is the number of documents and 300 is the size of embeddings. Why does it happen? Shouldn't be raised an exception? Eventually, how can we check if a document is missing or not?

Thank you in advance,
Claudio

**Comment by gojomo** [comment] 2015-11-10 21:16
This is caused by an unfortunate interaction between out internal method which converts a string-tag to an int-index (which returns None for not-present) and numpy array indexing, which returns that nested 1xCOUNTxSIZE result when passed None. 

Was a KeyError what you'd expected?

Until that's fixed, you can check whether a tag is in the trained set with `key in model.docvecs`.

**Comment by claudiogreco** [comment] 2015-11-10 22:49
Ok, I'll check whether a tag is in the trained set using your suggestion for now. Thank you for your help.

**Comment by tmylk** [comment] 2016-01-09 20:34
@gojomo should this be closed as a workaround exists?

**Comment by gojomo** [comment] 2016-01-10 09:49
@tmylk no, there should really be a KeyError (rather than a giant nested array) when the requested key isn't present. I'll prep a fix before next week.

**Comment by gojomo** [comment] 2016-01-16 03:28
Fixed by #582.

**Closed by gojomo** 2016-01-16 03:28 UTC
